"""Export a saved report (report_store.py) as a standalone file:

- Markdown: plain data, no interactivity - a chart becomes a small data
  table instead of an image (no headless-render step needed).
- HTML: a genuinely interactive page - Chart.js/Leaflet load from CDN and
  render real charts/maps client-side the moment the file is opened in any
  browser, reusing the same block vocabulary and chart shapes the app's
  own frontend already renders (ChartCanvas.jsx/MapCanvas.jsx/
  FlowMapCanvas.jsx) - no server-side rendering step at all.

The HTML template is built with plain string.replace() on __MARKERS__,
not an f-string/.format() - the template's own CSS/JS is full of literal
{ } braces, which an f-string would require doubling everywhere (highly
error-prone); a placeholder-token template sidesteps that entirely.
"""
import json

PALETTE = ['#e8590c', '#2f6fed', '#1e8e3e', '#d92d20', '#7c4dff', '#0891b2', '#b45309', '#6d4c41']


def _escape_html(s):
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _md_table(columns, rows):
    header = "| " + " | ".join(str(c) for c in columns) + " |"
    sep = "| " + " | ".join("---" for _ in columns) + " |"
    body = "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)
    return "\n".join([header, sep, body])


def _chart_as_md(chart):
    ctype = chart.get("type")
    title = chart.get("title", "Chart")
    if ctype == "map":
        rows = [[p.get("label", ""), p.get("lat"), p.get("lng"), p.get("value", "")] for p in chart.get("points", [])]
        return f"**{title}** (map)\n\n" + _md_table(["Label", "Lat", "Lng", "Value"], rows)
    if ctype == "od_map":
        rows = [[f.get("origin_label", ""), f.get("dest_label", ""), f.get("value", "")] for f in chart.get("flows", [])]
        return f"**{title}** (origin-destination map)\n\n" + _md_table(["Origin", "Destination", "Value"], rows)
    labels = chart.get("labels") or []
    data = chart.get("data") or []
    return f"**{title}** ({ctype})\n\n" + _md_table(["Label", "Value"], list(zip(labels, data)))


def to_markdown(report):
    lines = [f"# {report['title']}", ""]
    for block in report.get("blocks", []):
        btype = block.get("type")
        if btype == "text":
            lines.append(block.get("content", ""))
        elif btype == "table":
            lines.append(_md_table(block.get("columns", []), block.get("rows", [])))
        elif btype == "chart":
            lines.append(_chart_as_md(block.get("chart", {})))
        lines.append("")
    return "\n".join(lines)


_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>__TITLE__</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked@12.0.2/marked.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css">
<script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
  body { background:#f7f7f9; color:#1b1c1f; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; max-width:900px; margin:0 auto; padding:2.5rem 1.5rem 4rem; line-height:1.6; }
  h1 { font-size:1.6rem; margin-bottom:.25rem; }
  .meta { color:#5b5d66; font-size:.85rem; margin-bottom:2rem; }
  .block { margin:1.75rem 0; }
  .chart-card { background:#ffffff; border:1px solid #e4e4ea; border-radius:12px; padding:1.25rem; box-shadow:0 1px 2px rgba(16,17,20,.04); }
  .chart-title { font-weight:600; margin-bottom:.75rem; font-size:.95rem; }
  canvas { max-height:360px; }
  .map { height:360px; border-radius:10px; overflow:hidden; }
  table { border-collapse:collapse; width:100%; font-size:.85rem; }
  th, td { border:1px solid #e4e4ea; padding:.4rem .7rem; text-align:left; }
  th { background:#f1f1f4; }
  a { color:#e8590c; }
  code { background:#f1f1f4; padding:.1rem .35rem; border-radius:.3rem; }
</style>
</head>
<body>
<h1>__TITLE__</h1>
<div class="meta">Generated by Chatterbase &middot; __CREATED_AT__</div>
<div id="blocks"></div>
<script>
const PALETTE = __PALETTE_JSON__;
const blocks = __BLOCKS_JSON__;
const root = document.getElementById('blocks');
const OSM_TILE_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';

function el(tag, cls) { const e = document.createElement(tag); if (cls) e.className = cls; return e; }

function renderText(content) {
  const div = el('div', 'block');
  div.innerHTML = marked.parse(content || '');
  root.appendChild(div);
}

function renderTable(block) {
  const wrap = el('div', 'block');
  const table = el('table');
  const thead = el('thead');
  const htr = el('tr');
  (block.columns || []).forEach((c) => { const th = el('th'); th.textContent = c; htr.appendChild(th); });
  thead.appendChild(htr); table.appendChild(thead);
  const tbody = el('tbody');
  (block.rows || []).forEach((r) => {
    const tr = el('tr');
    r.forEach((c) => { const td = el('td'); td.textContent = c; tr.appendChild(td); });
    tbody.appendChild(tr);
  });
  table.appendChild(tbody); wrap.appendChild(table); root.appendChild(wrap);
}

function renderPointMap(wrap, chart) {
  const mapDiv = el('div', 'map'); wrap.appendChild(mapDiv); root.appendChild(wrap);
  const map = L.map(mapDiv);
  L.tileLayer(OSM_TILE_URL, { attribution: '&copy; OpenStreetMap contributors', maxZoom: 19 }).addTo(map);
  const pts = (chart.points || []).filter((p) => Number.isFinite(p.lat) && Number.isFinite(p.lng));
  if (!pts.length) { map.setView([20, 0], 2); return; }
  const vals = pts.map((p) => Number.isFinite(p.value) ? p.value : 1);
  const maxV = Math.max(...vals, 1), minV = Math.min(...vals, 0);
  pts.forEach((p) => {
    const v = Number.isFinite(p.value) ? p.value : 1;
    const r = 6 + (maxV > minV ? ((v - minV) / (maxV - minV)) * 18 : 0);
    L.circleMarker([p.lat, p.lng], { radius: r, color: '#e8590c', weight: 1.5, fillColor: '#e8590c', fillOpacity: 0.55 })
      .addTo(map).bindTooltip(p.label || (p.lat.toFixed(3) + ', ' + p.lng.toFixed(3)));
  });
  map.fitBounds(L.latLngBounds(pts.map((p) => [p.lat, p.lng])).pad(0.25), { maxZoom: 12 });
}

function renderFlowMap(wrap, chart) {
  const mapDiv = el('div', 'map'); wrap.appendChild(mapDiv); root.appendChild(wrap);
  const map = L.map(mapDiv);
  L.tileLayer(OSM_TILE_URL, { attribution: '&copy; OpenStreetMap contributors', maxZoom: 19 }).addTo(map);
  const flows = (chart.flows || []).filter((f) => [f.origin_lat, f.origin_lng, f.dest_lat, f.dest_lng].every(Number.isFinite));
  if (!flows.length) { map.setView([20, 0], 2); return; }
  const all = [];
  flows.forEach((f) => {
    const o = [f.origin_lat, f.origin_lng], d = [f.dest_lat, f.dest_lng];
    L.polyline([o, d], { color: '#e8590c', weight: 2.5, opacity: 0.65 }).addTo(map)
      .bindTooltip((f.origin_label || 'Origin') + ' \\u2192 ' + (f.dest_label || 'Destination'));
    L.circleMarker(o, { radius: 5, color: '#1e8e3e', fillColor: '#1e8e3e', fillOpacity: 0.9 }).addTo(map);
    L.circleMarker(d, { radius: 5, color: '#d92d20', fillColor: '#d92d20', fillOpacity: 0.9 }).addTo(map);
    all.push(o, d);
  });
  map.fitBounds(L.latLngBounds(all).pad(0.25), { maxZoom: 12 });
}

function renderClassicChart(wrap, chart) {
  const canvas = el('canvas'); wrap.appendChild(canvas); root.appendChild(wrap);
  const isPie = chart.type === 'pie' || chart.type === 'doughnut';
  const labels = chart.labels || [], data = chart.data || [];
  const colors = chart.colors && chart.colors.length ? chart.colors : PALETTE;
  new Chart(canvas, {
    type: chart.type || 'bar',
    data: { labels, datasets: [{
      label: chart.title || '', data,
      backgroundColor: isPie ? labels.map((_, i) => colors[i % colors.length]) : colors[0] + 'e0',
      borderColor: isPie ? '#ffffff' : colors[0], borderWidth: isPie ? 2 : 1,
      borderRadius: chart.type === 'bar' ? 6 : 0, tension: chart.type === 'line' ? 0.35 : 0,
    }] },
    options: {
      responsive: true,
      plugins: { legend: { display: isPie, labels: { color: '#5b5d66' } } },
      scales: isPie ? {} : {
        x: { ticks: { color: '#5b5d66' }, grid: { color: '#eceef1' } },
        y: { ticks: { color: '#5b5d66' }, grid: { color: '#eceef1' }, beginAtZero: true },
      },
    },
  });
}

function renderChart(chart) {
  const wrap = el('div', 'block chart-card');
  const h = el('div', 'chart-title'); h.textContent = chart.title || 'Chart'; wrap.appendChild(h);
  if (chart.type === 'map') renderPointMap(wrap, chart);
  else if (chart.type === 'od_map') renderFlowMap(wrap, chart);
  else renderClassicChart(wrap, chart);
}

blocks.forEach((b) => {
  if (b.type === 'text') renderText(b.content);
  else if (b.type === 'table') renderTable(b);
  else if (b.type === 'chart') renderChart(b.chart || {});
});
</script>
</body>
</html>"""


def to_html(report):
    return (
        _HTML_TEMPLATE
        .replace("__TITLE__", _escape_html(report.get("title", "Report")))
        .replace("__CREATED_AT__", _escape_html(report.get("created_at", "")))
        .replace("__PALETTE_JSON__", json.dumps(PALETTE))
        .replace("__BLOCKS_JSON__", json.dumps(report.get("blocks", [])))
    )
